version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.12-2.1.1
    restart: on-failure:3
    ports:
      - "9092:9092"
      - "9093:9093"
    depends_on:
      - zookeeper
    environment:
      KAFKA_CREATE_TOPICS: 'test-toipic-0:3:1,test-topic-1:3:1'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_ADVERTISED_HOST_NAME: 'localhost'
      KAFKA_ADVERTISED_PORT: '9092'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_MESSAGE_MAX_BYTES: 200000000
    # volumes:
    #   - /var/run/docker.sock:/var/run/docker.sock
  kafka-manager:
    image: hlebalbau/kafka-manager:stable
    ports:
      - "9000:9000" # visit kafka-manager at http://127.0.0.1:9000
    depends_on:
      - kafka
    environment:
      ZK_HOSTS: "zookeeper:2181"